const K='corpulMeu.entries.v2';
let entries=JSON.parse(localStorage.getItem(K)||localStorage.getItem('corpulMeu.entries.v1')||'[]');
let tab='journal',date=today(),modal=false,currentType='IN';
const Q={IN:['Cafea','Apa','Mic dejun','Pranz','Gustare','Medicament'],OUT:['Urinare','Scaun','Transpiratie'],STARE:['Durere de cap','Balonare','Oboseala','Energie','Foame','Anxietate'],ACTIVITATE:['Somn','Trezire','Mers','Sport','Munca','Stres']};
function today(){let d=new Date(),o=d.getTimezoneOffset()*60000;return new Date(d-o).toISOString().slice(0,10)}
function save(){localStorage.setItem(K,JSON.stringify(entries))}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function shell(c){return `<div class=shell>${c}</div><button class=plus onclick="openComposer()">+</button><nav class=nav>${[['journal','Jurnal'],['calendar','Calendar'],['insights','Insights'],['settings','Setari']].map(x=>`<button class="${tab===x[0]?'on':''}" onclick="setTab('${x[0]}')">${x[1]}</button>`).join('')}</nav>${modal?composer():''}`}
function render(){app.innerHTML=tab==='journal'?journal():tab==='calendar'?calendar():tab==='insights'?insights():settings()}
window.setTab=t=>{tab=t;render()};window.openComposer=()=>{currentType='IN';modal=true;render()};window.closeComposer=()=>{modal=false;render()};
function journal(){let ds=[-2,-1,0,1,2].map(n=>{let d=new Date();d.setDate(d.getDate()+n);let o=d.getTimezoneOffset()*60000;return new Date(d-o).toISOString().slice(0,10)}),list=entries.filter(e=>e.date===date).sort((a,b)=>a.time.localeCompare(b.time));return shell(`<div class=eyebrow>Jurnal personal</div><h1>Corpul meu</h1><div class=days>${ds.map(d=>`<button class="day ${d===date?'on':''}" onclick="date='${d}';render()"><b>${d.slice(8)}</b></button>`).join('')}</div><div class="row between" style="margin-top:20px"><b>Cronologie</b><span class=muted>${list.length} inregistrari</span></div>${list.length?list.map(e=>`<div class="card entry"><div class=time>${e.time}</div><div><span class="pill ${e.type}">${e.type}</span><div style="font-weight:700;margin-top:7px">${esc(e.name)}</div>${e.amount?`<div class=muted>${esc(e.amount)} ${esc(e.unit)}</div>`:e.intensity?`<div class=muted>Intensitate ${e.intensity}/10</div>`:''}</div><button class=delete onclick="removeEntry('${e.id}')">x</button></div>`).join(''):'<div class="card empty">Nicio inregistrare. Apasa +.</div>'}`)}
window.removeEntry=id=>{entries=entries.filter(e=>e.id!==id);save();render()};
function composer(){return `<div class=modal><div class=shell><div class="row between"><button class=secondary onclick="closeComposer()">Inchide</button><b>Inregistrare noua</b><span></span></div><div class=types style="margin-top:20px">${Object.keys(Q).map(t=>`<button data-type="${t}" class="${currentType===t?'on':''}" onclick="pickType('${t}')">${t}</button>`).join('')}</div><div class=card><div class=eyebrow>Ce?</div><input id=name placeholder="Scrie sau alege rapid"><div class=chips style="margin-top:10px">${Q[currentType].map((x,i)=>`<button onclick="quickPick(${i})">+ ${x}</button>`).join('')}</div></div><div class=grid2><div class=card><div class=eyebrow>Ora</div><input id=time type=time value="${new Date().toTimeString().slice(0,5)}"></div>${currentType==='IN'?`<div class=card><div class=eyebrow>Cantitate</div><input id=amount inputmode=decimal placeholder=250><select id=unit><option>ml</option><option>g</option><option>buc</option><option>mg</option></select></div>`:`<div class=card><div class=eyebrow>Data</div><b>${date}</b></div>`}</div>${currentType==='STARE'?`<div class=card><div class="row between"><span class=eyebrow>Intensitate</span><b id=iv>5/10</b></div><input id=ir type=range min=1 max=10 value=5 oninput="iv.textContent=this.value+'/10'"></div>`:''}<div class=card><div class=eyebrow>Notite</div><textarea id=notes rows=3></textarea></div><button class=primary onclick="addEntry()">Salveaza</button></div></div>`}
window.pickType=t=>{currentType=t;render()};window.quickPick=i=>{document.getElementById('name').value=Q[currentType][i]};
window.addEntry=()=>{let n=document.getElementById('name').value.trim();if(!n)return alert('Introdu ce s-a intamplat.');entries.push({id:(crypto.randomUUID?crypto.randomUUID():Date.now().toString()),date,time:document.getElementById('time').value,type:currentType,name:n,amount:currentType==='IN'?(document.getElementById('amount').value||''):null,unit:currentType==='IN'?document.getElementById('unit').value:'',intensity:currentType==='STARE'?document.getElementById('ir').value:null,notes:document.getElementById('notes').value});save();modal=false;currentType='IN';render()};
function calendar(){return shell(`<div class=eyebrow>Istoric</div><h1>Calendar</h1><div class="card empty">Calendarul complet ramane activ in versiunea urmatoare. Pentru test, foloseste zilele din Jurnal.</div>`)}
function analyze(){let s=[...entries].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)),r=[];for(let a of new Set(s.filter(e=>e.type==='IN').map(e=>e.name))){let ts=s.filter(e=>e.type==='IN'&&e.name===a);if(ts.length<2)continue;for(let b of new Set(s.filter(e=>['OUT','STARE'].includes(e.type)).map(e=>e.name))){let ds=[];for(let t of ts){let tt=new Date(`${t.date}T${t.time}`),x=s.find(e=>['OUT','STARE'].includes(e.type)&&e.name===b&&new Date(`${e.date}T${e.time}`)>tt&&new Date(`${e.date}T${e.time}`)-tt<=14400000);if(x)ds.push(Math.round((new Date(`${x.date}T${x.time}`)-tt)/60000))}if(ds.length)r.push({a,b,h:ds.length,n:ts.length,avg:Math.round(ds.reduce((p,c)=>p+c,0)/ds.length)})}}return r}
function insights(){let a=analyze();return shell(`<div class=eyebrow>Tipare personale</div><h1>Insights</h1>${a.length?a.map(i=>`<div class="card insight"><h3>${esc(i.a)} → ${esc(i.b)}</h3><div>${i.h}/${i.n} cazuri, medie ${i.avg} min.</div></div>`).join(''):'<div class="card empty">Mai sunt necesare date repetate.</div>'}<div class="card warn">Asocierile nu demonstreaza cauzalitate si nu reprezinta diagnostic medical.</div>`)}
function settings(){return shell(`<div class=eyebrow>Date</div><h1>Setari</h1><div class=card><b>${entries.length} inregistrari locale</b><p class=muted>Datele sunt pastrate in browser pe acest dispozitiv.</p></div>`)}
render();
