const STORE='corpulMeu.entries.v5';
const OBJECT_STORE='corpulMeu.objects.v2';
const DEFAULT_OBJECTS={IN:['250 ml apa','500 ml apa','Cafea','Mic dejun','Pranz','Gustare','Medicament'],OUT:['Urinare','Scaun','Transpiratie'],STARE:['Durere de cap','Balonare','Oboseala','Energie','Foame','Anxietate'],ACTIVITATE:['Somn','Trezire','Mers','Sport','Munca','Stres']};
function loadEntries(){for(const k of [STORE,'corpulMeu.entries.v4','corpulMeu.entries.v3','corpulMeu.entries.v2','corpulMeu.entries.v1']){const v=localStorage.getItem(k);if(v)try{return JSON.parse(v)}catch{}}return[]}
function cloneDefaults(){return JSON.parse(JSON.stringify(DEFAULT_OBJECTS))}
let entries=loadEntries(),objects=(()=>{try{return JSON.parse(localStorage.getItem(OBJECT_STORE))||cloneDefaults()}catch{return cloneDefaults()}})();
let tab='journal',selectedDate=localDate(),modal=false,editor=false,currentType='IN',draftId=null,status='';
function localDate(d=new Date()){const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)}
function saveEntries(){localStorage.setItem(STORE,JSON.stringify(entries))}function saveObjects(){localStorage.setItem(OBJECT_STORE,JSON.stringify(objects))}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmtDuration(m){m=Number(m||0);if(!m)return'';return m>=60?`${Math.floor(m/60)} h${m%60?' '+m%60+' min':''}`:`${m} min`}
function nav(content){return `<main class=shell>${content}</main><button class=plus data-action=open>+</button><nav class=nav>${[['journal','Jurnal'],['calendar','Calendar'],['insights','Insights'],['settings','Setari']].map(([k,v])=>`<button data-tab=${k} class="${tab===k?'on':''}">${v}</button>`).join('')}</nav>${modal?composer():''}${editor?objectEditor():''}`}
function render(){document.querySelector('#app').innerHTML=tab==='journal'?journal():tab==='calendar'?calendar():tab==='insights'?insights():settings()}
function journal(){let now=new Date(),days=[];for(let n=-4;n<=0;n++){let d=new Date(now);d.setDate(now.getDate()+n);days.push(localDate(d))}if(selectedDate>localDate())selectedDate=localDate();let list=entries.filter(e=>e.date===selectedDate).sort((a,b)=>a.time.localeCompare(b.time));return nav(`<div class=eyebrow>Jurnal personal</div><h1>Corpul meu</h1><div class=days>${days.map(d=>`<button class="day ${d===selectedDate?'on':''}" data-date=${d}><div class=muted>${new Date(d+'T12:00').toLocaleDateString('ro-RO',{weekday:'short'})}</div><b>${d.slice(8)}</b></button>`).join('')}</div><div class="row between" style="margin-top:20px"><b>Cronologie</b><span class=muted>${list.length} inregistrari</span></div>${list.length?list.map(entryCard).join(''):'<div class="card empty">Nicio inregistrare. Apasa +.</div>'}`)}
function entryCard(e){let extras=[];if(e.duration)extras.push('Durata '+fmtDuration(e.duration));if(e.intensity)extras.push('Intensitate '+e.intensity+'/10');if(e.notes)extras.push(e.notes);return `<div class=card style="padding:13px 14px"><div style="display:grid;grid-template-columns:64px 78px minmax(0,1fr) 22px;gap:7px;align-items:center"><div style="font-size:12px;font-weight:800;color:#64748b;text-align:left">${esc(e.time)}</div><span class="pill ${e.type}" style="font-size:12px;text-align:center">${e.type}</span><div style="font-size:14px;font-weight:700;text-align:left;overflow-wrap:anywhere">${esc(e.name)}</div><button class=delete data-delete="${e.id}">x</button></div>${extras.length?`<div class=muted style="margin-left:149px;margin-top:5px">${extras.map(esc).join(' · ')}</div>`:''}</div>`}
function draft(){return entries.find(e=>e.id===draftId)}
function composer(){let d=draft(),time=d?.time||new Date().toTimeString().slice(0,5),duration=d?.duration||'',name=d?.name||'',notes=d?.notes||'',intensity=d?.intensity||5;return `<div class=modal><div class=shell><div class="row between"><button class=secondary data-action=close>Inchide</button><b>Inregistrare noua</b><span></span></div><div class=types style="margin-top:20px">${Object.keys(objects).map(t=>`<button type=button data-type=${t} class="${currentType===t?'on':''}">${t}</button>`).join('')}</div><div class=grid2><div class=card><div class=eyebrow>Ora debut *</div><input id=time type=time value="${esc(time)}"></div><div class=card><div class=eyebrow>Durata</div><div class=row><input id=duration type=number min=1 step=1 inputmode=numeric placeholder="optional" value="${esc(duration)}"><span class=muted>min</span></div></div></div><div class=card><div class="row between"><div class=eyebrow>Obiect *</div><button type=button class=smallbtn data-action=editobjects>Edit</button></div><select id=name style="margin-top:10px"><option value="">Alege obiectul...</option>${objects[currentType].map(x=>`<option value="${esc(x)}" ${x===name?'selected':''}>${esc(x)}</option>`).join('')}</select></div>${currentType==='STARE'?`<div class=card><div class="row between"><span class=eyebrow>Intensitate</span><b id=iv>${intensity}/10</b></div><input id=ir type=range min=1 max=10 value=${intensity}></div>`:''}<div class=card><div class=eyebrow>Notite</div><textarea id=notes rows=3 placeholder="Detalii optionale">${esc(notes)}</textarea></div><div style="text-align:center;min-height:24px" class=muted id=savestatus>${status||'Tipul, ora si obiectul sunt obligatorii. Salvarea este automata.'}</div></div></div>`}
function objectEditor(){return `<div class=modal style="z-index:8"><div class=shell><div class="row between"><button class=secondary data-action=closeeditor>Inapoi</button><b>Obiecte ${currentType}</b><span></span></div><div class=card><div class=eyebrow>Adauga obiect</div><div class=row style="margin-top:8px"><input id=newobject placeholder="ex. 750 ml apa"><button class=smallbtn data-action=addobject>Adauga</button></div></div><div class=card>${objects[currentType].map((x,i)=>`<div class=row style="margin-bottom:8px"><input data-object-index=${i} value="${esc(x)}"><button class=smallbtn data-save-object=${i}>OK</button><button class=delete data-delete-object=${i}>x</button></div>`).join('')}</div></div></div>`}
function calendar(){return nav('<div class=eyebrow>Istoric</div><h1>Calendar</h1><div class="card empty">Calendarul complet va fi refinat dupa testul de utilizare.</div>')}
function insights(){return nav('<div class=eyebrow>Tipare personale</div><h1>Insights</h1><div class="card empty">Insights apar dupa ce aduni evenimente repetate.</div><div class="card warn">Asocierile nu demonstreaza cauzalitate si nu reprezinta diagnostic medical.</div>')}
function settings(){return nav(`<div class=eyebrow>Date</div><h1>Setari</h1><div class=card><b>${entries.length} inregistrari locale</b><p class=muted>Datele sunt pastrate local in acest browser.</p></div>`)}
function autosave(){if(!modal||editor)return;let time=document.querySelector('#time')?.value||'',name=document.querySelector('#name')?.value||'';if(!time||!name){status='Completeaza ora si obiectul.';let x=document.querySelector('#savestatus');if(x)x.textContent=status;return}let e=draft();if(!e){e={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),date:selectedDate,type:currentType};entries.push(e);draftId=e.id}e.type=currentType;e.time=time;e.name=name;e.duration=document.querySelector('#duration')?.value?Number(document.querySelector('#duration').value):null;e.intensity=currentType==='STARE'?Number(document.querySelector('#ir')?.value||5):null;e.notes=document.querySelector('#notes')?.value||'';saveEntries();status='✓ Salvat automat';let x=document.querySelector('#savestatus');if(x)x.textContent=status}
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.type){currentType=b.dataset.type;if(draftId){let d=draft();d.type=currentType;d.name='';d.intensity=currentType==='STARE'?5:null;saveEntries()}status='';render();return}if(b.dataset.tab){tab=b.dataset.tab;render();return}if(b.dataset.date){selectedDate=b.dataset.date;render();return}if(b.dataset.delete){entries=entries.filter(x=>x.id!==b.dataset.delete);saveEntries();render();return}if(b.dataset.action==='open'){currentType='IN';modal=true;editor=false;draftId=null;status='';render();return}if(b.dataset.action==='close'){modal=false;editor=false;draftId=null;status='';render();return}if(b.dataset.action==='editobjects'){autosave();editor=true;render();return}if(b.dataset.action==='closeeditor'){editor=false;render();return}if(b.dataset.action==='addobject'){let v=document.querySelector('#newobject').value.trim();if(v&&!objects[currentType].includes(v)){objects[currentType].push(v);saveObjects();render()}return}if(b.dataset.saveObject!==undefined){let i=Number(b.dataset.saveObject),v=document.querySelector(`[data-object-index="${i}"]`).value.trim();if(v){objects[currentType][i]=v;saveObjects();render()}return}if(b.dataset.deleteObject!==undefined){let i=Number(b.dataset.deleteObject);if(confirm('Stergi acest obiect?')){objects[currentType].splice(i,1);saveObjects();render()}return}});
document.addEventListener('change',e=>{if(['time','name','duration'].includes(e.target.id))autosave()});
document.addEventListener('input',e=>{if(e.target.id==='ir'){document.querySelector('#iv').textContent=e.target.value+'/10';autosave()}if(e.target.id==='notes')autosave()});
render();
